name: Build packages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build derivations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: cachix/install-nix-action@v31

      - name: Setup Cachix
        uses: cachix/cachix-action@v16
        with:
          name: uku3lig
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build
        run: |
          nix run \
            github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --systems 'x86_64-linux' \
            --option accept-flake-config true \
            --option allow-import-from-derivation false \
            --flake '.#hydraJobs'
